version: 2
updates:
- package-ecosystem: nuget
  directory: "/SRC.Sharp/"
  schedule:
    interval: daily
  groups:
    aspnetcore:
      patterns:
      - "Microsoft.AspNetCore*"
      update-types:
      - "minor"
      - "patch"
    selenium:
      patterns:
      - "Selenium*"
      update-types:
      - "minor"
      - "patch"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
