title: SRC#Help
email: koudenpa@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SRC#のヘルプページ
baseurl: ""
url: "https://yellow-pebble-0ddb1c400.azurestaticapps.net"
twitter_username: koudenpa
github_username: 7474

# Build settings
source: md
theme: minima
plugins: []
markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
permalink: pretty
encoding: UTF-8
