title: SRC#Help
email: koudenpa@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  SRC#のヘルプページ
baseurl: ""
url: "https://srch.7474.jp"
twitter_username: koudenpa
github_username: 7474

# Build settings
source: src
theme: just-the-docs
plugins: 
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: false

markdown_ext: "md"
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  auto_ids: true

permalink: pretty
encoding: UTF-8
