name: SRC#Help CI/CD

on:
  push:
    branches:
      - master
    paths: 
      - .github/workflows/azure-static-web-apps-yellow-pebble-0ddb1c400.yml
      - SRC.Sharp.Help/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master
    paths: 
      - .github/workflows/azure-static-web-apps-yellow-pebble-0ddb1c400.yml
      - SRC.Sharp.Help/**

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    environment:
      name: ${{ (github.event_name == 'push' && 'SRC#Help') || 'SRC#Help dev' }}
      url: ${{ (github.event_name == 'push' && 'https://srch.7474.jp/') || steps.builddeploy.outputs.static_web_app_url }}
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_PEBBLE_0DDB1C400 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/SRC.Sharp.Help/"
          api_location: "" 
          output_location: "_site" 

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    environment:
      name: 'SRC#Help dev'
      url: ''
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_PEBBLE_0DDB1C400 }}
          action: "close"
