name: E2E-SRCSForm

on:
  push

jobs:
  e2e-srcsform:
    name: Scenario test SRCSForm
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - run: dotnet publish SRC.Sharp/SRCSharpForm/SRCSharpForm.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false
    - run: >-
        powershell Start-Process
        -FilePath SRC.Sharp/SRCSharpForm/bin/Release/net5.0-windows/win-x64/publish/SRCSharpForm.exe
        -ArgumentList --console SRC.Sharp/SRCSharpFormTestWinAppDriver/Scenario/empty.eve
        -Wait
      
